# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea0a5a84dbc57377f6b2d49b2db5af2491ceafe51f38134fcdee4cebb8bd198df72fddac3d590e36347f2b156bb5e70bd0baf7f753624b17ffee0f92940b8f9

test:
  secret_key_base: 646e4f9d2849da67057bcddaa18fc15d52c45eaead19da3322ca2a6aa1b5b20e49630eeb40d0f01880582bd27efba5e42298a872f84fdba1e7d21cf8789e6555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
